
"""
app/modules/search/schemas/search_schema.py

Schemas for the search module.
"""

from typing import Any

from pydantic import Field, model_validator

from app.shared.schemas.base import BaseSchema


class SearchRequest(BaseSchema):
    """Request containing a stable repository identity and user's query."""

    repo_id: str | None = Field(
        default=None,
        description="UUID of a registered repository. Preferred identifier.",
    )
    repo_name: str | None = Field(
        default=None,
        description="Legacy repository name/full name accepted during migration.",
    )
    query: str = Field(..., min_length=3, max_length=1000)

    @model_validator(mode="after")
    def require_repository_identifier(self) -> "SearchRequest":
        if not (self.repo_id and self.repo_id.strip()) and not (
            self.repo_name and self.repo_name.strip()
        ):
            raise ValueError("Either repo_id or repo_name is required")
        return self


class QueryUnderstandingResponse(BaseSchema):
    """
    Response for the initial query-understanding pipeline.

    This is intentionally limited to:
    - intent classification
    - explicit parameter identification
    - query preprocessing
    """

    success: bool
    query: str

    intent: str | None = None
    parameters: dict[str, Any] = Field(default_factory=dict)
    confidence: float | None = None

    keywords: list[str] = Field(default_factory=list)
    identifiers: list[str] = Field(default_factory=list)
    file_paths: list[str] = Field(default_factory=list)
    repo_hint: str | None = None
    language_hint: str | None = None

    error: str | None = None


class AmbiguousCandidate(BaseSchema):
    """Describes one candidate when a symbol name exists in multiple files."""

    name: str
    file_path: str
    class_name: str | None = None
    start_line: int | None = None
    end_line: int | None = None
    score: float | None = None


class EvidenceItem(BaseSchema):
    """An item of evidence used to generate the response."""

    file_path: str
    snippet: str
    score: float


class SearchResponse(BaseSchema):
    """Compact public response for Code Explorer / RepoLens."""

    intent: str

    repository: dict[str, Any] | None = None

    target: dict[str, Any] | None = None

    requirement: str | None = None

    # Used mainly for FIX_BUG / OPTIMIZE / REFACTOR
    # to explain the existing problematic behavior.
    current_behavior: str | None = None

    # Human-readable explanation/recommendation.
    suggestion: str | None = None

    # Description of what needs to be changed.
    proposed_change: str | None = None

    # Actual corrected/proposed code generated by the analyzer.
    suggested_code: str | None = None

    confidence: str | None = None

    early_exit: dict[str, Any] | None = None

    # Populated when the query symbol exists in multiple files and
    # cannot be uniquely resolved. Lists every matching candidate so
    # the caller can prompt the user to be more specific.
    ambiguous_candidates: list[AmbiguousCandidate] = Field(default_factory=list)
