"""initial schema

Revision ID: 420732333362
Revises: 
Create Date: 2026-09-07 06:28:21.728665+00:00
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '420732333362'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chunk_registry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(length=2048), nullable=False),
    sa.Column('chunk_hash', sa.String(length=64), nullable=False),
    sa.Column('point_id', sa.String(length=36), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=True),
    sa.Column('end_line', sa.Integer(), nullable=True),
    sa.Column('chunk_type', sa.String(length=50), nullable=True),
    sa.Column('function_name', sa.String(length=512), nullable=True),
    sa.Column('class_name', sa.String(length=512), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('commit_sha', sa.String(length=40), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'chunk_hash', name='uq_chunk_registry_repo_chunk_hash')
    )
    op.create_index('ix_chunk_registry_chunk_hash', 'chunk_registry', ['chunk_hash'], unique=False)
    op.create_index('ix_chunk_registry_function', 'chunk_registry', ['function_name'], unique=False)
    op.create_index('ix_chunk_registry_point_id', 'chunk_registry', ['point_id'], unique=False)
    op.create_index('ix_chunk_registry_repo_file', 'chunk_registry', ['repository_id', 'file_path'], unique=False)
    op.create_index('ix_chunk_registry_repo_id', 'chunk_registry', ['repository_id'], unique=False)
    op.create_index(op.f('ix_chunk_registry_repository_id'), 'chunk_registry', ['repository_id'], unique=False)
    op.create_table('file_registry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(length=2048), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('blob_sha', sa.String(length=40), nullable=True),
    sa.Column('commit_sha', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'file_path', name='uq_file_registry_repo_path')
    )
    op.create_index('ix_file_registry_file_hash', 'file_registry', ['file_hash'], unique=False)
    op.create_index('ix_file_registry_repo_id', 'file_registry', ['repository_id'], unique=False)
    op.create_index('ix_file_registry_repo_path', 'file_registry', ['repository_id', 'file_path'], unique=False)
    op.create_index(op.f('ix_file_registry_repository_id'), 'file_registry', ['repository_id'], unique=False)
    op.create_index('ix_file_registry_status', 'file_registry', ['status'], unique=False)
    op.create_table('ingestion_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('stage', sa.String(length=100), nullable=False),
    sa.Column('commit_sha', sa.String(length=40), nullable=True),
    sa.Column('target_branch', sa.String(length=255), nullable=True),
    sa.Column('total_files', sa.Integer(), nullable=False),
    sa.Column('processed_files', sa.Integer(), nullable=False),
    sa.Column('skipped_files', sa.Integer(), nullable=False),
    sa.Column('deleted_files', sa.Integer(), nullable=False),
    sa.Column('total_chunks', sa.Integer(), nullable=False),
    sa.Column('processed_chunks', sa.Integer(), nullable=False),
    sa.Column('reused_chunks', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_traceback', sa.Text(), nullable=True),
    sa.Column('checkpoint_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ingestion_jobs_celery_task', 'ingestion_jobs', ['celery_task_id'], unique=False)
    op.create_index('ix_ingestion_jobs_repo_status', 'ingestion_jobs', ['repository_id', 'status'], unique=False)
    op.create_index(op.f('ix_ingestion_jobs_repository_id'), 'ingestion_jobs', ['repository_id'], unique=False)
    op.create_index('ix_ingestion_jobs_status', 'ingestion_jobs', ['status'], unique=False)
    op.create_table('webhook_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('delivery_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=True),
    sa.Column('payload_hash', sa.String(length=64), nullable=True),
    sa.Column('ref', sa.String(length=255), nullable=True),
    sa.Column('head_commit_sha', sa.String(length=40), nullable=True),
    sa.Column('pusher', sa.String(length=255), nullable=True),
    sa.Column('added_files_count', sa.Integer(), nullable=False),
    sa.Column('modified_files_count', sa.Integer(), nullable=False),
    sa.Column('removed_files_count', sa.Integer(), nullable=False),
    sa.Column('ingestion_job_id', sa.UUID(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_job_id'], ['ingestion_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('delivery_id'),
    sa.UniqueConstraint('delivery_id', name='uq_webhook_events_delivery_id')
    )
    op.create_index('ix_webhook_events_event_type', 'webhook_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_webhook_events_ingestion_job_id'), 'webhook_events', ['ingestion_job_id'], unique=False)
    op.create_index('ix_webhook_events_repo_id', 'webhook_events', ['repository_id'], unique=False)
    op.create_index(op.f('ix_webhook_events_repository_id'), 'webhook_events', ['repository_id'], unique=False)
    op.create_index('ix_webhook_events_status', 'webhook_events', ['status'], unique=False)
    op.add_column('repositories', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('repositories', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('repositories', 'default_branch',
               existing_type=sa.VARCHAR(length=255),
               server_default=None,
               existing_nullable=False)
    op.alter_column('repositories', 'qdrant_collection',
               existing_type=sa.VARCHAR(length=255),
               server_default=None,
               existing_nullable=False)
    op.alter_column('repositories', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.create_index('ix_repositories_full_name', 'repositories', ['full_name'], unique=False)
    op.create_index('ix_repositories_owner', 'repositories', ['owner'], unique=False)
    op.create_index('ix_repositories_status', 'repositories', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_repositories_status', table_name='repositories')
    op.drop_index('ix_repositories_owner', table_name='repositories')
    op.drop_index('ix_repositories_full_name', table_name='repositories')
    op.alter_column('repositories', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'PENDING'::character varying"),
               existing_nullable=False)
    op.alter_column('repositories', 'qdrant_collection',
               existing_type=sa.VARCHAR(length=255),
               server_default=sa.text("'code_chunks'::character varying"),
               existing_nullable=False)
    op.alter_column('repositories', 'default_branch',
               existing_type=sa.VARCHAR(length=255),
               server_default=sa.text("'main'::character varying"),
               existing_nullable=False)
    op.drop_column('repositories', 'updated_at')
    op.drop_column('repositories', 'created_at')
    op.drop_index('ix_webhook_events_status', table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_repository_id'), table_name='webhook_events')
    op.drop_index('ix_webhook_events_repo_id', table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_ingestion_job_id'), table_name='webhook_events')
    op.drop_index('ix_webhook_events_event_type', table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index('ix_ingestion_jobs_status', table_name='ingestion_jobs')
    op.drop_index(op.f('ix_ingestion_jobs_repository_id'), table_name='ingestion_jobs')
    op.drop_index('ix_ingestion_jobs_repo_status', table_name='ingestion_jobs')
    op.drop_index('ix_ingestion_jobs_celery_task', table_name='ingestion_jobs')
    op.drop_table('ingestion_jobs')
    op.drop_index('ix_file_registry_status', table_name='file_registry')
    op.drop_index(op.f('ix_file_registry_repository_id'), table_name='file_registry')
    op.drop_index('ix_file_registry_repo_path', table_name='file_registry')
    op.drop_index('ix_file_registry_repo_id', table_name='file_registry')
    op.drop_index('ix_file_registry_file_hash', table_name='file_registry')
    op.drop_table('file_registry')
    op.drop_index(op.f('ix_chunk_registry_repository_id'), table_name='chunk_registry')
    op.drop_index('ix_chunk_registry_repo_id', table_name='chunk_registry')
    op.drop_index('ix_chunk_registry_repo_file', table_name='chunk_registry')
    op.drop_index('ix_chunk_registry_point_id', table_name='chunk_registry')
    op.drop_index('ix_chunk_registry_function', table_name='chunk_registry')
    op.drop_index('ix_chunk_registry_chunk_hash', table_name='chunk_registry')
    op.drop_table('chunk_registry')
    # ### end Alembic commands ###

