"""add_github_webhook_id_to_repositories

Revision ID: 9fe690579423
Revises: 1db0f73b9d25
Create Date: 2026-09-10 12:25:14.396561+00:00
"""
from alembic import op
import sqlalchemy as sa


revision = '9fe690579423'
down_revision = '1db0f73b9d25'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repos', sa.Column('github_webhook_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repos', 'github_webhook_id')
    # ### end Alembic commands ###

