"""initial_schema

Revision ID: 1db0f73b9d25
Revises: 
Create Date: 2026-09-04 07:48:43.395525+00:00
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '1db0f73b9d25'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repo_url', sa.String(length=500), nullable=False),
    sa.Column('repo_name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('default_branch', sa.String(length=255), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('access_token_ref', sa.String(length=255), nullable=True),
    sa.Column('qdrant_collection_name', sa.String(length=255), nullable=False),
    sa.Column('last_indexed_commit_sha', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_url')
    )
    op.create_table('ingestion_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('trigger_source', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('commit_sha', sa.Text(), nullable=False),
    sa.Column('previous_commit_sha', sa.Text(), nullable=True),
    sa.Column('files_scanned', sa.Integer(), nullable=False),
    sa.Column('files_changed', sa.Integer(), nullable=False),
    sa.Column('files_unchanged', sa.Integer(), nullable=False),
    sa.Column('files_deleted', sa.Integer(), nullable=False),
    sa.Column('chunks_upserted', sa.Integer(), nullable=False),
    sa.Column('chunks_deleted', sa.Integer(), nullable=False),
    sa.Column('chunks_reused', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_jobs_repo_id'), 'ingestion_jobs', ['repo_id'], unique=False)
    op.create_table('chunk_registry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('chunk_hash', sa.Text(), nullable=False),
    sa.Column('symbol_name', sa.Text(), nullable=True),
    sa.Column('symbol_type', sa.String(length=50), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=True),
    sa.Column('end_line', sa.Integer(), nullable=True),
    sa.Column('embedding_model', sa.Text(), nullable=True),
    sa.Column('embedding_version', sa.Text(), nullable=True),
    sa.Column('qdrant_point_id', sa.Text(), nullable=True),
    sa.Column('last_seen_job_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['last_seen_job_id'], ['ingestion_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chunk_registry_qdrant_point_id'), 'chunk_registry', ['qdrant_point_id'], unique=False)
    op.create_index(op.f('ix_chunk_registry_repo_id'), 'chunk_registry', ['repo_id'], unique=False)
    op.create_table('file_hashes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('blob_sha', sa.Text(), nullable=False),
    sa.Column('file_hash', sa.Text(), nullable=False),
    sa.Column('last_commit_sha', sa.Text(), nullable=True),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('last_seen_job_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['last_seen_job_id'], ['ingestion_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_hashes_repo_id'), 'file_hashes', ['repo_id'], unique=False)
    op.create_table('webhook_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=True),
    sa.Column('delivery_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('signature_valid', sa.Boolean(), nullable=False),
    sa.Column('payload_raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('ingestion_job_id', sa.UUID(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_job_id'], ['ingestion_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('delivery_id')
    )
    op.create_index(op.f('ix_webhook_events_repo_id'), 'webhook_events', ['repo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_registry',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('repository_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=2048), autoincrement=False, nullable=False),
    sa.Column('language', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('file_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('blob_sha', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('commit_sha', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('file_size_bytes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('file_registry_repository_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('file_registry_pkey')),
    sa.UniqueConstraint('repository_id', 'file_path', name=op.f('uq_file_registry_repo_path'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_file_registry_status'), 'file_registry', ['status'], unique=False)
    op.create_index(op.f('ix_file_registry_repository_id'), 'file_registry', ['repository_id'], unique=False)
    op.create_index(op.f('ix_file_registry_repo_path'), 'file_registry', ['repository_id', 'file_path'], unique=False)
    op.create_index(op.f('ix_file_registry_repo_id'), 'file_registry', ['repository_id'], unique=False)
    op.create_index(op.f('ix_file_registry_file_hash'), 'file_registry', ['file_hash'], unique=False)
    op.create_table('repositories',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('github_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('owner', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('default_branch', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('current_commit_sha', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('qdrant_collection', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('github_repo_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('github_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('repositories_pkey')),
    sa.UniqueConstraint('full_name', name=op.f('repositories_full_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('github_url', name=op.f('repositories_github_url_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_repositories_status'), 'repositories', ['status'], unique=False)
    op.create_index(op.f('ix_repositories_owner'), 'repositories', ['owner'], unique=False)
    op.create_index(op.f('ix_repositories_full_name'), 'repositories', ['full_name'], unique=False)
    op.drop_index(op.f('ix_webhook_events_repo_id'), table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_file_hashes_repo_id'), table_name='file_hashes')
    op.drop_table('file_hashes')
    op.drop_index(op.f('ix_chunk_registry_repo_id'), table_name='chunk_registry')
    op.drop_index(op.f('ix_chunk_registry_qdrant_point_id'), table_name='chunk_registry')
    op.drop_table('chunk_registry')
    op.drop_index(op.f('ix_ingestion_jobs_repo_id'), table_name='ingestion_jobs')
    op.drop_table('ingestion_jobs')
    op.drop_table('repos')
    # ### end Alembic commands ###

