"""
app/modules/search/retrieval/dense_search.py

Dense vector retrieval using the pre-computed Voyage query embedding
and Qdrant similarity search.

The query embedding is generated by the Step 6 retrieval pipeline stage.
This class is responsible only for querying Qdrant and converting the
returned points into RetrievedChunk objects.
"""

from __future__ import annotations

from app.infrastructure.qdrant.vector_repository import search_vectors
from app.modules.search.domain.search_domain import RetrievedChunk, SearchContext


class DenseSearch:
    """Perform dense vector retrieval against Qdrant."""

    async def search(
        self,
        context: SearchContext,
        limit: int = 20,
    ) -> list[RetrievedChunk]:
        """
        Retrieve the most similar code chunks using the query vector.

        Qdrant is responsible for calculating similarity. The configured
        collection should use cosine distance for vector similarity.

        The repository ID is passed to the vector repository so that
        retrieval remains isolated to the requested repository.
        """

        # ---------------------------------------------------------
        # 1. Validate search limit
        # ---------------------------------------------------------
        if limit <= 0:
            return []

        # ---------------------------------------------------------
        # 2. Validate Qdrant collection
        # ---------------------------------------------------------
        if not context.qdrant_collection:
            print("DENSE SEARCH: Missing Qdrant collection")
            return []

        # ---------------------------------------------------------
        # 3. Validate repository ID
        # ---------------------------------------------------------
        if not context.repo_id:
            print("DENSE SEARCH: Missing repository ID")
            return []

        # ---------------------------------------------------------
        # 4. Validate query embedding
        # ---------------------------------------------------------
        if not context.query_vector:
            print("DENSE SEARCH: Query vector is missing or empty")
            return []

        # ---------------------------------------------------------
        # 5. DEBUG: Verify query embedding exists
        # ---------------------------------------------------------
        print("\n========== DENSE SEARCH DEBUG ==========")

        print("QDRANT COLLECTION:", context.qdrant_collection)
        print("REPOSITORY ID:", context.repo_id)

        print("QUERY VECTOR TYPE:", type(context.query_vector))
        print("QUERY VECTOR DIMENSION:", len(context.query_vector))

        print(
            "QUERY VECTOR FIRST 5 VALUES:",
            context.query_vector[:5],
        )

        print("QUERY VECTOR EMPTY:", not bool(context.query_vector))

        print("========================================\n")

        # ---------------------------------------------------------
        # 6. Search Qdrant using the query embedding
        # ---------------------------------------------------------
        scored_points = await search_vectors(
            collection_name=context.qdrant_collection,
            query_vector=context.query_vector,
            limit=limit,
            repo_id=context.repo_id,
        )

        # ---------------------------------------------------------
        # 7. Convert Qdrant points into RetrievedChunk objects
        # ---------------------------------------------------------
        chunks: list[RetrievedChunk] = []

        for point in scored_points or []:
            payload = point.payload or {}

            chunks.append(
                RetrievedChunk(
                    chunk_hash=payload.get("chunk_hash", ""),
                    file_path=payload.get("file_path", ""),
                    content=payload.get("content", ""),
                    score=float(point.score),
                    metadata=payload,
                )
            )

        # ---------------------------------------------------------
        # 8. DEBUG: Retrieval result count
        # ---------------------------------------------------------
        print(
            f"DENSE SEARCH: Retrieved {len(chunks)} chunks from Qdrant"
        )

        return chunks