
"""
app/modules/search/retrieval/dense_search.py

Dense vector retrieval using the pre-computed Voyage query embedding
and Qdrant similarity search.

The query embedding is generated by the Step 6 retrieval pipeline stage.
This class is responsible only for querying Qdrant and converting the
returned points into RetrievedChunk objects.
"""

from __future__ import annotations

from app.infrastructure.qdrant.vector_repository import search_vectors
from app.modules.search.domain.search_domain import RetrievedChunk, SearchContext


class DenseSearch:
    """Perform dense vector retrieval against Qdrant."""

    async def search(
        self,
        context: SearchContext,
        limit: int = 20,
    ) -> list[RetrievedChunk]:
        """
        Retrieve the most similar code chunks using the query vector.

        Qdrant is responsible for calculating similarity. The configured
        collection should use cosine distance for vector similarity.

        The repository ID is passed to the vector repository so that
        retrieval remains isolated to the requested repository.
        """

        if limit <= 0:
            return []

        if not context.qdrant_collection:
            return []

        if not context.repo_id:
            return []

        if not context.query_vector:
            return []

        scored_points = await search_vectors(
            collection_name=context.qdrant_collection,
            query_vector=context.query_vector,
            limit=limit,
            repo_id=context.repo_id,
        )

        chunks: list[RetrievedChunk] = []

        for point in scored_points or []:
            payload = point.payload or {}

            chunks.append(
                RetrievedChunk(
                    chunk_hash=payload.get("chunk_hash", ""),
                    file_path=payload.get("file_path", ""),
                    content=payload.get("content", ""),
                    score=float(point.score),
                    metadata=payload,
                )
            )

        return chunks

